name: thermodynamic-budgets
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - numpy
  - xarray
  - matplotlib
  - netcdf4
  - cartopy
  - cmocean
  - dask
  - hdf5
  - pip
  - pip:
    - xarray-regrid
  
